CREATE TABLE TLDS(
   country VARCHAR(78) NOT NULL
  ,tld     VARCHAR(5) NOT NULL
  ,PRIMARY KEY(country,tld)
);
INSERT INTO TLDS(country,tld) VALUES ('Afghanistan','.af');
INSERT INTO TLDS(country,tld) VALUES ('Åland','.ax');
INSERT INTO TLDS(country,tld) VALUES ('Albania','.al');
INSERT INTO TLDS(country,tld) VALUES ('Algeria','.dz');
INSERT INTO TLDS(country,tld) VALUES ('American Samoa','.as');
INSERT INTO TLDS(country,tld) VALUES ('Andorra','.ad');
INSERT INTO TLDS(country,tld) VALUES ('Angola','.ao');
INSERT INTO TLDS(country,tld) VALUES ('Anguilla','.ai');
INSERT INTO TLDS(country,tld) VALUES ('Antarctica','.aq');
INSERT INTO TLDS(country,tld) VALUES ('Antigua and Barbuda','.ag');
INSERT INTO TLDS(country,tld) VALUES ('Argentina','.ar');
INSERT INTO TLDS(country,tld) VALUES ('Armenia','.am');
INSERT INTO TLDS(country,tld) VALUES ('Aruba','.aw');
INSERT INTO TLDS(country,tld) VALUES ('Ascension Island','.ac');
INSERT INTO TLDS(country,tld) VALUES ('Australia','.au');
INSERT INTO TLDS(country,tld) VALUES ('Austria','.at');
INSERT INTO TLDS(country,tld) VALUES ('Azerbaijan','.az');
INSERT INTO TLDS(country,tld) VALUES ('Bahamas','.bs');
INSERT INTO TLDS(country,tld) VALUES ('Bahrain','.bh');
INSERT INTO TLDS(country,tld) VALUES ('Bangladesh','.bd');
INSERT INTO TLDS(country,tld) VALUES ('Barbados','.bb');
INSERT INTO TLDS(country,tld) VALUES ('Basque Country','.eus');
INSERT INTO TLDS(country,tld) VALUES ('Belarus','.by');
INSERT INTO TLDS(country,tld) VALUES ('Belgium','.be');
INSERT INTO TLDS(country,tld) VALUES ('Belize','.bz');
INSERT INTO TLDS(country,tld) VALUES ('Benin','.bj');
INSERT INTO TLDS(country,tld) VALUES ('Bermuda','.bm');
INSERT INTO TLDS(country,tld) VALUES ('Bhutan','.bt');
INSERT INTO TLDS(country,tld) VALUES ('Bolivia','.bo');
INSERT INTO TLDS(country,tld) VALUES ('Bonaire','.bq');
INSERT INTO TLDS(country,tld) VALUES ('Bonaire','.an');
INSERT INTO TLDS(country,tld) VALUES ('Bonaire','.nl');
INSERT INTO TLDS(country,tld) VALUES ('Bosnia and Herzegovina','.ba');
INSERT INTO TLDS(country,tld) VALUES ('Botswana','.bw');
INSERT INTO TLDS(country,tld) VALUES ('Bouvet Island','.bv');
INSERT INTO TLDS(country,tld) VALUES ('Brazil','.br');
INSERT INTO TLDS(country,tld) VALUES ('British Indian Ocean Territory','.io');
INSERT INTO TLDS(country,tld) VALUES ('British Virgin Islands','.vg');
INSERT INTO TLDS(country,tld) VALUES ('Brunei','.bn');
INSERT INTO TLDS(country,tld) VALUES ('Bulgaria','.bg');
INSERT INTO TLDS(country,tld) VALUES ('Burkina Faso','.bf');
INSERT INTO TLDS(country,tld) VALUES ('Burma (officially: Myanmar)','.mm');
INSERT INTO TLDS(country,tld) VALUES ('Burundi','.bi');
INSERT INTO TLDS(country,tld) VALUES ('Cambodia','.kh');
INSERT INTO TLDS(country,tld) VALUES ('Cameroon','.cm');
INSERT INTO TLDS(country,tld) VALUES ('Canada','.ca');
INSERT INTO TLDS(country,tld) VALUES ('Cape Verde (in Portuguese: Cabo Verde)','.cv');
INSERT INTO TLDS(country,tld) VALUES ('Catalonia','.cat');
INSERT INTO TLDS(country,tld) VALUES ('Cayman Islands','.ky');
INSERT INTO TLDS(country,tld) VALUES ('Central African Republic','.cf');
INSERT INTO TLDS(country,tld) VALUES ('Chad','.td');
INSERT INTO TLDS(country,tld) VALUES ('Chile','.cl');
INSERT INTO TLDS(country,tld) VALUES ('China, People’s Republic of','.cn');
INSERT INTO TLDS(country,tld) VALUES ('Christmas Island','.cx');
INSERT INTO TLDS(country,tld) VALUES ('Cocos (Keeling) Islands','.cc');
INSERT INTO TLDS(country,tld) VALUES ('Colombia','.co');
INSERT INTO TLDS(country,tld) VALUES ('Comoros','.km');
INSERT INTO TLDS(country,tld) VALUES ('Congo, Democratic Republic of the (Congo-Kinshasa)','.cd');
INSERT INTO TLDS(country,tld) VALUES ('Congo, Republic of the (Congo-Brazzaville)','.cg');
INSERT INTO TLDS(country,tld) VALUES ('Cook Islands','.ck');
INSERT INTO TLDS(country,tld) VALUES ('Costa Rica','.cr');
INSERT INTO TLDS(country,tld) VALUES ('Côte d’Ivoire (Ivory Coast)','.ci');
INSERT INTO TLDS(country,tld) VALUES ('Croatia','.hr');
INSERT INTO TLDS(country,tld) VALUES ('Cuba','.cu');
INSERT INTO TLDS(country,tld) VALUES ('Curaçao','.cw');
INSERT INTO TLDS(country,tld) VALUES ('Cyprus','.cy');
INSERT INTO TLDS(country,tld) VALUES ('Czechia (Czech Republic)','.cz');
INSERT INTO TLDS(country,tld) VALUES ('Denmark','.dk');
INSERT INTO TLDS(country,tld) VALUES ('Djibouti','.dj');
INSERT INTO TLDS(country,tld) VALUES ('Dominica','.dm');
INSERT INTO TLDS(country,tld) VALUES ('Dominican Republic','.do');
INSERT INTO TLDS(country,tld) VALUES ('East Timor (Timor-Leste)','.tl');
INSERT INTO TLDS(country,tld) VALUES ('East Timor (Timor-Leste)','.tp');
INSERT INTO TLDS(country,tld) VALUES ('Ecuador','.ec');
INSERT INTO TLDS(country,tld) VALUES ('Egypt','.eg');
INSERT INTO TLDS(country,tld) VALUES ('El Salvador','.sv');
INSERT INTO TLDS(country,tld) VALUES ('Equatorial Guinea','.gq');
INSERT INTO TLDS(country,tld) VALUES ('Eritrea','.er');
INSERT INTO TLDS(country,tld) VALUES ('Estonia','.ee');
INSERT INTO TLDS(country,tld) VALUES ('Ethiopia','.et');
INSERT INTO TLDS(country,tld) VALUES ('European Union','.eu');
INSERT INTO TLDS(country,tld) VALUES ('Falkland Islands','.fk');
INSERT INTO TLDS(country,tld) VALUES ('Faeroe Islands','.fo');
INSERT INTO TLDS(country,tld) VALUES ('Federated States of Micronesia','.fm');
INSERT INTO TLDS(country,tld) VALUES ('Fiji','.fj');
INSERT INTO TLDS(country,tld) VALUES ('Finland','.fi');
INSERT INTO TLDS(country,tld) VALUES ('France','.fr');
INSERT INTO TLDS(country,tld) VALUES ('French Guiana','.gf');
INSERT INTO TLDS(country,tld) VALUES ('French Polynesia','.pf');
INSERT INTO TLDS(country,tld) VALUES ('French Southern and Antarctic Lands','.tf');
INSERT INTO TLDS(country,tld) VALUES ('Gabon (officially: Gabonese Republic)','.ga');
INSERT INTO TLDS(country,tld) VALUES ('Galicia','.gal');
INSERT INTO TLDS(country,tld) VALUES ('Gambia','.gm');
INSERT INTO TLDS(country,tld) VALUES ('Gaza Strip (Gaza)','.ps');
INSERT INTO TLDS(country,tld) VALUES ('Georgia','.ge');
INSERT INTO TLDS(country,tld) VALUES ('Germany','.de');
INSERT INTO TLDS(country,tld) VALUES ('Ghana','.gh');
INSERT INTO TLDS(country,tld) VALUES ('Gibraltar','.gi');
INSERT INTO TLDS(country,tld) VALUES ('Greece','.gr');
INSERT INTO TLDS(country,tld) VALUES ('Greenland','.gl');
INSERT INTO TLDS(country,tld) VALUES ('Grenada','.gd');
INSERT INTO TLDS(country,tld) VALUES ('Guadeloupe','.gp');
INSERT INTO TLDS(country,tld) VALUES ('Guam','.gu');
INSERT INTO TLDS(country,tld) VALUES ('Guatemala','.gt');
INSERT INTO TLDS(country,tld) VALUES ('Guernsey','.gg');
INSERT INTO TLDS(country,tld) VALUES ('Guinea','.gn');
INSERT INTO TLDS(country,tld) VALUES ('Guinea-Bissau','.gw');
INSERT INTO TLDS(country,tld) VALUES ('Guyana','.gy');
INSERT INTO TLDS(country,tld) VALUES ('Haiti','.ht');
INSERT INTO TLDS(country,tld) VALUES ('Heard Island and McDonald Islands','.hm');
INSERT INTO TLDS(country,tld) VALUES ('Honduras','.hn');
INSERT INTO TLDS(country,tld) VALUES ('Hong Kong','.hk');
INSERT INTO TLDS(country,tld) VALUES ('Hungary','.hu');
INSERT INTO TLDS(country,tld) VALUES ('Iceland','.is');
INSERT INTO TLDS(country,tld) VALUES ('India','.in');
INSERT INTO TLDS(country,tld) VALUES ('Indonesia','.id');
INSERT INTO TLDS(country,tld) VALUES ('Iran','.ir');
INSERT INTO TLDS(country,tld) VALUES ('Iraq','.iq');
INSERT INTO TLDS(country,tld) VALUES ('Ireland','.ie');
INSERT INTO TLDS(country,tld) VALUES ('Isle of Man','.im');
INSERT INTO TLDS(country,tld) VALUES ('Israel','.il');
INSERT INTO TLDS(country,tld) VALUES ('Italy','.it');
INSERT INTO TLDS(country,tld) VALUES ('Jamaica','.jm');
INSERT INTO TLDS(country,tld) VALUES ('Japan','.jp');
INSERT INTO TLDS(country,tld) VALUES ('Jersey','.je');
INSERT INTO TLDS(country,tld) VALUES ('Jordan','.jo');
INSERT INTO TLDS(country,tld) VALUES ('Kazakhstan','.kz');
INSERT INTO TLDS(country,tld) VALUES ('Kenya','.ke');
INSERT INTO TLDS(country,tld) VALUES ('Kiribati','.ki');
INSERT INTO TLDS(country,tld) VALUES ('Kuwait','.kw');
INSERT INTO TLDS(country,tld) VALUES ('Kyrgyzstan','.kg');
INSERT INTO TLDS(country,tld) VALUES ('Laos','.la');
INSERT INTO TLDS(country,tld) VALUES ('Latvia','.lv');
INSERT INTO TLDS(country,tld) VALUES ('Lebanon','.lb');
INSERT INTO TLDS(country,tld) VALUES ('Lesotho','.ls');
INSERT INTO TLDS(country,tld) VALUES ('Liberia','.lr');
INSERT INTO TLDS(country,tld) VALUES ('Libya','.ly');
INSERT INTO TLDS(country,tld) VALUES ('Liechtenstein','.li');
INSERT INTO TLDS(country,tld) VALUES ('Lithuania','.lt');
INSERT INTO TLDS(country,tld) VALUES ('Luxembourg','.lu');
INSERT INTO TLDS(country,tld) VALUES ('Macau','.mo');
INSERT INTO TLDS(country,tld) VALUES ('Macedonia, Republic of (the former Yugoslav Republic of Macedonia, FYROM)','.mk');
INSERT INTO TLDS(country,tld) VALUES ('Madagascar','.mg');
INSERT INTO TLDS(country,tld) VALUES ('Malawi','.mw');
INSERT INTO TLDS(country,tld) VALUES ('Malaysia','.my');
INSERT INTO TLDS(country,tld) VALUES ('Maldives','.mv');
INSERT INTO TLDS(country,tld) VALUES ('Mali','.ml');
INSERT INTO TLDS(country,tld) VALUES ('Malta','.mt');
INSERT INTO TLDS(country,tld) VALUES ('Marshall Islands','.mh');
INSERT INTO TLDS(country,tld) VALUES ('Martinique','.mq');
INSERT INTO TLDS(country,tld) VALUES ('Mauritania','.mr');
INSERT INTO TLDS(country,tld) VALUES ('Mauritius','.mu');
INSERT INTO TLDS(country,tld) VALUES ('Mayotte','.yt');
INSERT INTO TLDS(country,tld) VALUES ('Mexico','.mx');
INSERT INTO TLDS(country,tld) VALUES ('Moldova','.md');
INSERT INTO TLDS(country,tld) VALUES ('Monaco','.mc');
INSERT INTO TLDS(country,tld) VALUES ('Mongolia','.mn');
INSERT INTO TLDS(country,tld) VALUES ('Montenegro','.me');
INSERT INTO TLDS(country,tld) VALUES ('Montserrat','.ms');
INSERT INTO TLDS(country,tld) VALUES ('Morocco','.ma');
INSERT INTO TLDS(country,tld) VALUES ('Mozambique','.mz');
INSERT INTO TLDS(country,tld) VALUES ('Myanmar','.mm');
INSERT INTO TLDS(country,tld) VALUES ('Namibia','.na');
INSERT INTO TLDS(country,tld) VALUES ('Nauru','.nr');
INSERT INTO TLDS(country,tld) VALUES ('Nepal','.np');
INSERT INTO TLDS(country,tld) VALUES ('Netherlands','.nl');
INSERT INTO TLDS(country,tld) VALUES ('New Caledonia','.nc');
INSERT INTO TLDS(country,tld) VALUES ('New Zealand','.nz');
INSERT INTO TLDS(country,tld) VALUES ('Nicaragua','.ni');
INSERT INTO TLDS(country,tld) VALUES ('Niger','.ne');
INSERT INTO TLDS(country,tld) VALUES ('Nigeria','.ng');
INSERT INTO TLDS(country,tld) VALUES ('Niue','.nu');
INSERT INTO TLDS(country,tld) VALUES ('Norfolk Island','.nf');
INSERT INTO TLDS(country,tld) VALUES ('North Cyprus (unrecognised, self-declared state)','.nc');
INSERT INTO TLDS(country,tld) VALUES ('North Cyprus (unrecognised, self-declared state)','.tr');
INSERT INTO TLDS(country,tld) VALUES ('North Korea','.kp');
INSERT INTO TLDS(country,tld) VALUES ('Northern Mariana Islands','.mp');
INSERT INTO TLDS(country,tld) VALUES ('Norway','.no');
INSERT INTO TLDS(country,tld) VALUES ('Oman','.om');
INSERT INTO TLDS(country,tld) VALUES ('Pakistan','.pk');
INSERT INTO TLDS(country,tld) VALUES ('Palau','.pw');
INSERT INTO TLDS(country,tld) VALUES ('Palestine','.ps');
INSERT INTO TLDS(country,tld) VALUES ('Panama','.pa');
INSERT INTO TLDS(country,tld) VALUES ('Papua New Guinea','.pg');
INSERT INTO TLDS(country,tld) VALUES ('Paraguay','.py');
INSERT INTO TLDS(country,tld) VALUES ('Peru','.pe');
INSERT INTO TLDS(country,tld) VALUES ('Philippines','.ph');
INSERT INTO TLDS(country,tld) VALUES ('Pitcairn Islands','.pn');
INSERT INTO TLDS(country,tld) VALUES ('Poland','.pl');
INSERT INTO TLDS(country,tld) VALUES ('Portugal','.pt');
INSERT INTO TLDS(country,tld) VALUES ('Puerto Rico','.pr');
INSERT INTO TLDS(country,tld) VALUES ('Qatar','.qa');
INSERT INTO TLDS(country,tld) VALUES ('Romania','.ro');
INSERT INTO TLDS(country,tld) VALUES ('Russia','.ru');
INSERT INTO TLDS(country,tld) VALUES ('Rwanda','.rw');
INSERT INTO TLDS(country,tld) VALUES ('Réunion Island','.re');
INSERT INTO TLDS(country,tld) VALUES ('Saba','.bq');
INSERT INTO TLDS(country,tld) VALUES ('Saba','.an');
INSERT INTO TLDS(country,tld) VALUES ('Saint Barthélemy (informally also referred to as Saint Barth’s or Saint Barts)','.bl');
INSERT INTO TLDS(country,tld) VALUES ('Saint Barthélemy (informally also referred to as Saint Barth’s or Saint Barts)','.gp');
INSERT INTO TLDS(country,tld) VALUES ('Saint Barthélemy (informally also referred to as Saint Barth’s or Saint Barts)','.fr');
INSERT INTO TLDS(country,tld) VALUES ('Saint Helena','.sh');
INSERT INTO TLDS(country,tld) VALUES ('Saint Kitts and Nevis','.kn');
INSERT INTO TLDS(country,tld) VALUES ('Saint Lucia','.lc');
INSERT INTO TLDS(country,tld) VALUES ('Saint Martin (officially the Collectivity of Saint Martin)','.mf');
INSERT INTO TLDS(country,tld) VALUES ('Saint Martin (officially the Collectivity of Saint Martin)','.gp');
INSERT INTO TLDS(country,tld) VALUES ('Saint Martin (officially the Collectivity of Saint Martin)','.fr');
INSERT INTO TLDS(country,tld) VALUES ('Saint-Pierre and Miquelon','.pm');
INSERT INTO TLDS(country,tld) VALUES ('Saint Vincent and the Grenadines','.vc');
INSERT INTO TLDS(country,tld) VALUES ('Samoa','.ws');
INSERT INTO TLDS(country,tld) VALUES ('San Marino','.sm');
INSERT INTO TLDS(country,tld) VALUES ('São Tomé and Príncipe','.st');
INSERT INTO TLDS(country,tld) VALUES ('Saudi Arabia','.sa');
INSERT INTO TLDS(country,tld) VALUES ('Senegal','.sn');
INSERT INTO TLDS(country,tld) VALUES ('Serbia','.rs');
INSERT INTO TLDS(country,tld) VALUES ('Seychelles','.sc');
INSERT INTO TLDS(country,tld) VALUES ('Sierra Leone','.sl');
INSERT INTO TLDS(country,tld) VALUES ('Singapore','.sg');
INSERT INTO TLDS(country,tld) VALUES ('Sint Eustatius','.bq');
INSERT INTO TLDS(country,tld) VALUES ('Sint Eustatius','.an');
INSERT INTO TLDS(country,tld) VALUES ('Sint Eustatius','.nl');
INSERT INTO TLDS(country,tld) VALUES ('Sint Maarten','.sx');
INSERT INTO TLDS(country,tld) VALUES ('Sint Maarten','.an');
INSERT INTO TLDS(country,tld) VALUES ('Slovakia','.sk');
INSERT INTO TLDS(country,tld) VALUES ('Slovenia','.si');
INSERT INTO TLDS(country,tld) VALUES ('Solomon Islands','.sb');
INSERT INTO TLDS(country,tld) VALUES ('Somalia','.so');
INSERT INTO TLDS(country,tld) VALUES ('Somaliland','.so');
INSERT INTO TLDS(country,tld) VALUES ('South Africa','.za');
INSERT INTO TLDS(country,tld) VALUES ('South Georgia and the South Sandwich Islands','.gs');
INSERT INTO TLDS(country,tld) VALUES ('South Korea','.kr');
INSERT INTO TLDS(country,tld) VALUES ('South Sudan','.ss');
INSERT INTO TLDS(country,tld) VALUES ('Spain','.es');
INSERT INTO TLDS(country,tld) VALUES ('Sri Lanka','.lk');
INSERT INTO TLDS(country,tld) VALUES ('Sudan','.sd');
INSERT INTO TLDS(country,tld) VALUES ('Suriname','.sr');
INSERT INTO TLDS(country,tld) VALUES ('Svalbard and Jan Mayen Islands','.sj');
INSERT INTO TLDS(country,tld) VALUES ('Swaziland','.sz');
INSERT INTO TLDS(country,tld) VALUES ('Sweden','.se');
INSERT INTO TLDS(country,tld) VALUES ('Switzerland','.ch');
INSERT INTO TLDS(country,tld) VALUES ('Syria','.sy');
INSERT INTO TLDS(country,tld) VALUES ('Taiwan','.tw');
INSERT INTO TLDS(country,tld) VALUES ('Tajikistan','.tj');
INSERT INTO TLDS(country,tld) VALUES ('Tanzania','.tz');
INSERT INTO TLDS(country,tld) VALUES ('Thailand','.th');
INSERT INTO TLDS(country,tld) VALUES ('Togo','.tg');
INSERT INTO TLDS(country,tld) VALUES ('Tokelau','.tk');
INSERT INTO TLDS(country,tld) VALUES ('Tonga','.to');
INSERT INTO TLDS(country,tld) VALUES ('Trinidad & Tobago','.tt');
INSERT INTO TLDS(country,tld) VALUES ('Tunisia','.tn');
INSERT INTO TLDS(country,tld) VALUES ('Turkey','.tr');
INSERT INTO TLDS(country,tld) VALUES ('Turkmenistan','.tm');
INSERT INTO TLDS(country,tld) VALUES ('Turks and Caicos Islands','.tc');
INSERT INTO TLDS(country,tld) VALUES ('Tuvalu','.tv');
INSERT INTO TLDS(country,tld) VALUES ('Uganda','.ug');
INSERT INTO TLDS(country,tld) VALUES ('Ukraine','.ua');
INSERT INTO TLDS(country,tld) VALUES ('United Arab Emirates (UAE)','.ae');
INSERT INTO TLDS(country,tld) VALUES ('United Kingdom (UK)','.uk');
INSERT INTO TLDS(country,tld) VALUES ('United States of America (USA)','.us');
INSERT INTO TLDS(country,tld) VALUES ('United States Virgin Islands','.vi');
INSERT INTO TLDS(country,tld) VALUES ('Uruguay','.uy');
INSERT INTO TLDS(country,tld) VALUES ('Uzbekistan','.uz');
INSERT INTO TLDS(country,tld) VALUES ('Vanuatu','.vu');
INSERT INTO TLDS(country,tld) VALUES ('Vatican City','.va');
INSERT INTO TLDS(country,tld) VALUES ('Venezuela','.ve');
INSERT INTO TLDS(country,tld) VALUES ('Vietnam','.vn');
INSERT INTO TLDS(country,tld) VALUES ('Wallis and Futuna','.wf');
INSERT INTO TLDS(country,tld) VALUES ('Western Sahara','.eh');
INSERT INTO TLDS(country,tld) VALUES ('Western Sahara','.ma');
INSERT INTO TLDS(country,tld) VALUES ('Yemen','.ye');
INSERT INTO TLDS(country,tld) VALUES ('Zambia','.zm');
INSERT INTO TLDS(country,tld) VALUES ('Zimbabwe','.zw');
